import Head from 'next/head'
import React from 'react'
import NavbarUser from '../../components/NavbarUser'
import ProfileDetails from '../../components/ProfileDetails'

export default function Profile() {
  return (
    <div>
        <Head>
        <title>Wefinder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavbarUser />
        <div className="flex flex-row  max-w-7xl mx-auto">
            <ProfileDetails/>
        </div>
      </main>
    </div>
  )
}
