import Head from "next/head";
import React, { useEffect, useState } from "react";
import NavbarUser from "../components/NavbarUser";
import SidebarChat from "../components/SidebarChat";
import styled from "styled-components";
import { useAuth } from "../context/AuthContext";

export default function Chat() {
  const {user, logOut} = useAuth();
  return (
    <div>
      <Head>
        <title>Wefinder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavbarUser user={user} logOut={logOut}/>
        <div className="flex flex-row  max-w-7xl mx-auto">
            <SidebarChat user={user}/> 
            <Backgroud/>
        </div>
      </main>
    </div>
  );
}

const Backgroud = styled.div`
  background-color: whitesmoke;
  width: 100%;
`;