import { collection, doc, getDoc, getDocs, onSnapshot, orderBy } from "firebase/firestore";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import NavbarUser from "../components/NavbarUser";
import SidebarChat from "../components/SidebarChat";
import { db } from "../firebase";
import styled from "styled-components";

export default function Chat() {

  return (
    <div>
      <Head>
        <title>Wefinder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavbarUser />
        <div className="flex flex-row  max-w-7xl mx-auto">
            <SidebarChat/> 
            <Backgroud/>
        </div>
      </main>
    </div>
  );
}

const Backgroud = styled.div`
  background-color: whitesmoke;
  width: 100%;
`;