import Head from "next/head";
import React from "react";
import NavbarUser from "../components/NavbarUser";
import SidebarChat from "../components/SidebarChat";

export default function chat() {
  return (
    <div>
      <Head>
        <title>Wefinder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavbarUser />
        <div className="flex flex-row min-h-screen max-w-7xl mx-auto">
            <SidebarChat/> 
        </div>
      </main>
    </div>
  );
}
