import Head from "next/head";
import Feed from "../components/Feed";
import LeftSide from "../components/LeftSide";
import Sidebar from "../components/Sidebar";
import Widgets from "../components/Widgets";

export default function Home({newsResults}) {
  return (
    <div>
      <Head>
        <title>Wefinder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Sidebar />
        <div className="flex flex-row min-h-screen max-w-7xl mx-auto">
          <LeftSide />
          <Feed/> 
          <Widgets newsResults={newsResults.articles}/> 
          {/* <Modal/> */}
        </div>
        
      </main>
    </div>
  );
}

//https://saurav.tech/NewsAPI/top-headlines/category/bussiness/us.json

export async function getServerSideProps() {
  const newsResults = await fetch(
    "https://saurav.tech/NewsAPI/top-headlines/category/business/us.json"
  ).then((res) => res.json());

  // Who to follow section
  return {
    props: {
      newsResults,
    },
  };
}