import Head from "next/head";
import Feed from "../components/Feed";
import LeftSide from "../components/LeftSide";
import Sidebar from "../components/Sidebar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Wefinder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Sidebar />
        <div className="flex flex-row min-h-screen max-w-7xl mx-auto">
          <LeftSide />
          <Feed/> 
          {/* <Widgets/> */}
          {/* <Modal/> */}
        </div>
        
      </main>
    </div>
  );
}
