import { doc, serverTimestamp, setDoc } from "firebase/firestore";
import { signIn, useSession } from "next-auth/react";
import Head from "next/head";
import { useEffect } from "react";
import CommentModal from "../components/CommentModal";
import Feed from "../components/Feed";
import LeftSide from "../components/LeftSide";
import NavbarUser from "../components/NavbarUser";
import Widgets from "../components/Widgets";


export default function Home({newsResults, randomUsersResults}) {
  return (
    <div>
      <Head>
        <title>Wefinder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        <NavbarUser/> 
        <div className="flex flex-row min-h-screen max-w-7xl mx-auto">
          <LeftSide />
          <Feed/>
          {/* <Widgets newsResults={newsResults.articles} randomUsersResults={randomUsersResults.results}/>   */}
          <CommentModal/>
        </div>
        
      </main>
    </div>
  );
}

//https://saurav.tech/NewsAPI/top-headlines/category/bussiness/us.json


/* export async function getServerSideProps() {
  const newsResults = await fetch(
    "https://saurav.tech/NewsAPI/top-headlines/category/business/us.json"
  ).then((res) => res.json());

  // Who to follow section

  const randomUsersResults = await fetch(
    "https://randomuser.me/api/?results=30&inc=name,login,picture"
  ).then((res) => res.json());

  return {
    props: {
      newsResults,
      randomUsersResults,
    },
  };
} */