import Head from 'next/head'
import React from 'react'
import NavbarUser from '../components/NavbarUser'
import Network from '../components/Network'
import { useAuth } from '../context/AuthContext';

export default function Red() {
  const {user, logOut} = useAuth();
  return (
    <div>
      <Head>
        <title>Wefinder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavbarUser user={user} logOut={logOut}/>
        <div className="flex flex-row  max-w-7xl mx-auto border-b border-graySubTitle">
            <Network className=""/>
        </div>
      </main>
    </div>
  )
}
